on: push
name: Example Workflow
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: LaunchDarkly Code References
      uses: launchdarkly/find-code-references@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LD_ACCESS_TOKEN: ${{ secrets.ACCESS }}
        LD_PROJ_KEY: flask-app-training
        LD_CONTEXT_LINES: "< 0"
